export const DASHBOARD = "Dashboard";
export const CREATE_COURSE = "Create course";
export const PREVIEW_HOME =  "Preview home page";
export const PREVIEW_AFTER_LOGIN =  "Preview after login page";
export const VIEW_WELCOME_SCREEN = "View Welcome Screen";
export const HELP = "Help";
export const NEW_SIGNUP = "New signups";
export const REVENUE = "Revenue";
export const PRODUCT_SALES = "Product sales";
export const ACTIVE_LEARNERS = "Active learners";
export const SEE_ALL ="see all";
export const INVITE = "Invite";
export const UPGRADE = "Upgrade now! >>"